

CREATE DATABASE banco_teste_automacao;

USE banco_teste_automacao;

CREATE TABLE massas(
	IDMASSAS int(11) NOT NULL AUTO_INCREMENT,
	NAME_PRODUCT VARCHAR(45) DEFAULT NULL,
	CUSTOMIZATION VARCHAR(45) DEFAULT NULL,
	DISPLAY VARCHAR(600) DEFAULT NULL,
	DISPLAY_RESOLUTION VARCHAR(45) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
	DISPLAY_SIZE VARCHAR(45) DEFAULT NULL,
	MEMORY VARCHAR(45) DEFAULT NULL,
	OPERATING_SYSTEM VARCHAR(45) DEFAULT NULL,
	PROCESSOR VARCHAR(255) DEFAULT NULL,
	TOUCHSCREEN VARCHAR(45) DEFAULT NULL,
	WEIGHT VARCHAR(45) DEFAULT NULL,
	COLOR VARCHAR(45) DEFAULT NULL,
	PRIMARY KEY(IDMASSAS)
) ENGINE=InnoDB AUTO_INCREMENT=2 
	DEFAULT CHARSET=utf8mb4 
	COLLATE=utf8mb4_0900_ai_ci;
	
INSERT INTO massas(
	NAME_PRODUCT, 
	CUSTOMIZATION, 
	DISPLAY, 
	DISPLAY_RESOLUTION, 
	DISPLAY_SIZE, 
	MEMORY, 
	OPERATING_SYSTEM, 
	PROCESSOR, 
	TOUCHSCREEN, 
	WEIGHT, 
	COLOR
) VALUES(
	'HP PAVILION 15Z TOUCH LAPTOP',
	'Simplicity',
	'15.6-inch diagonal Full HD WLED-backlit Display (1920x1080) Touchscreen',
	'1920x1080',
	'15.6',
	'16GB DDR3 - 2 DIMM',
	'Windows 10',
	'AMD Quad-Core A10-8700P Processor + AMD Radeon(TM) R6 Graphics',
	'Yes',
	'5.51 lb',
	'GRAY'
);

	
	
	
	
	
	
	
	
	